version: 2
updates: 
  - package-ecosystem: gradle
    directory: "junitpractice/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: gradle
    directory: "tasklist/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10