name: Java CI for tasklist (./gradle build test)
on: 
  pull_request:
jobs:
  build:
    name: build by Gradle
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'feature') || contains(github.head_ref, 'dependabot/gradle/tasklist')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          cache: gradle
      - name: Build with Gradle
        run: |
         cd tasklist
         ./gradlew build test
