name: Java CI for tasklist (./gradle build test)
on: 
  pull_request:
jobs:
  build:
    name: build by Gradle
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'feature')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Gradle
        run: |
         cd tasklist
         ./gradlew build test
